services:
  - type: web
    name: emotiondetection-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: HF_HOME
        value: /tmp/huggingface
