services:
  - type: web
    name: emotion-chatbot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        value: "your-secret-key"
